version: '3.9'
services:
  image_downloader:
    build: ./docker_download
    volumes:
      - ./images:/app/images
  image_metadata_extractor:
    build: ./docker_extract
    depends_on:
      - image_downloader
    volumes:
      - ./images:/app/images
      - ./metadata:/app/metadata
  image_extracter:
    build: ./extract
    depends_on:
      - image_downloader
      - image_metadata_extractor
    volumes:
      - ./images:/app/images
      - ./metadata:/app/metadata

