version: '3.9'
services:
  image_downloader:
    build: 
      context : .
      dockerfile : ./docker_download/dockerfile
    volumes:
      - ./images:/app/images
  image_metadata_extractor:
    build: 
      context : .
      dockerfile : ./docker_extract/dockerfile
    depends_on:
      - image_downloader
    volumes:
      - ./images:/app/images
      - ./metadata:/app/metadata
  image_extracter:
    build: 
      context : .
      dockerfile : ./docker_extract/dockerfile
    depends_on:
      - image_downloader
      - image_metadata_extractor
    volumes:
      - ./images:/app/images
      - ./metadata:/app/metadata

