# Utiliser une image de base Python
FROM python:3.8-slim-buster

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers du répertoire courant dans le conteneur
ADD . /app

# Copiez le script Python dans l'image
COPY download.py /app

#test
RUN ls /app

# Installer les dépendances
RUN pip install requests 

# Exécuter le script
CMD ["python", "download.py"]