# Dockerfile
FROM python:3.8-slim

# Installez les dépendances
RUN pip install torch torchvision pillow transformers opencv-python colorthief pytesseract imageai opencv-python-headless

# Téléchargez les fichiers de modèle nécessaires
RUN mkdir /root/.torch/models
RUN wget -P /root/.torch/models https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth

# Créez les répertoires de travail
RUN mkdir /app
RUN mkdir /app/images
RUN mkdir /app/metadata

# Définir le répertoire de travail
WORKDIR /app

# Copiez le script Python dans l'image
COPY analyse.py /app

# Exécutez le script Python lorsque le conteneur est démarré
CMD ["python", "./analyse.py"]